{
 "title": "Pagespeed Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "testpages",
    "label": "URL",
    "query": "from(bucket:\"performance\")\n  |> range(start: -4w)\n  |> filter(fn: (r) => r._measurement == \"lighthouse_performance_data\")\n  |> group()\n  |> keep(columns: [\"url\"])\n  |> unique(column: \"url\")"
   },
   {
    "name": "strategy",
    "label": "Strategy",
    "query": "from(bucket:\"performance\")\n  |> range(start: -4w)\n  |> filter(fn: (r) => r._measurement == \"lighthouse_performance_data\")\n  |> group()\n  |> keep(columns: [\"strategy\"])\n  |> unique(column: \"strategy\")"
   }
  ]
 },
 "panels": [
  { "title": "Field-Data (CrUX)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_lcp\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"LCP\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fid\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"FID\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_cls\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"CLS\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fcp\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"FCP\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fcp_proportions_good\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"GOOD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fcp_proportions_average\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"AVERAGE\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fcp_proportions_bad\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"BAD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_lcp\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"LCP\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_lcp_proportions_good\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"GOOD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_lcp_proportions_average\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"AVERAGE\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_lcp_proportions_bad\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"BAD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fid\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"FID\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fid_proportions_good\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"GOOD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fid_proportions_average\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"AVERAGE\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_fid_proportions_bad\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"BAD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_cls\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"CLS\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_cls_proportions_good\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"GOOD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_cls_proportions_average\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"AVERAGE\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"crux_cls_proportions_bad\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"BAD\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Lab-Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Latest Pagespeed Score",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"score\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"Score (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Score",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\nmultByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value * x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"score\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> multByX(x:100.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"Score (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"fcp\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"FCP (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"lcp\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"LCP (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"cls\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:10.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"CLS (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"speed_index\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"Speed Index (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time to Interactive (TTI)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"tti\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"TTI (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Blocking Time (TBT)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"tbt\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"TBT (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"fcp\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"FCP (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"lcp\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"LCP (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"cls\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:10.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"CLS (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"speed_index\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"Speed Index (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time to Interactive (TTI)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\n// Function definition\ndivByX = (tables=<-, x) =>\n  tables\n    |> map(fn: (r) => ({ r with _value: r._value / x}))\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"tti\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  |> divByX(x:1000.0)\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"TTI (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Blocking Time (TBT)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "FinalOutput = [\"_field\",\"_time\",\"_value\"]\n\nRawSeries = from(bucket:\"performance\")\n  |> range(start: ${__from:date:iso}, stop: ${__to:date:iso})\n  |> filter(fn:(r) =>\n    r._measurement == \"lighthouse_performance_data\" and\n    r._field == \"tbt\" and\n    r.url == ${testpages:doublequote} and\n    r.strategy == ${strategy:doublequote}\n  )\n  \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field: \"TBT (Lighthouse v\"+r.lighthouse_version+\")\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}